spring:
  # 애플리케이션 이름
  application:
    name : climbing-record-app

# 데이터 베이스 연결 설정
  datasource:
    url: jdbc:mysql://localhost:3306/climbing?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: climbing
    password: climbing

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

jwt:
  secret: "It'sMyClimbingAppSecretKeyForJWTGeneration3391"
  expiration: 86400000


server:
  port: 8080